### ISSUE TITLE
UTF-8 text doesn't work well

### ISSUE THREAD

**Issue by rogpeppe** [dgryski/go-sequitur#3]
If the grammar input is UTF-8, the resulting pretty-printed grammar does not contain well-formed UTF-8 text.

Demonstrated by the following code:

	package main
	
	import (
		"bytes"
		"fmt"
		"log"
		"unicode/utf8"
	
		sequitur "github.com/dgryski/go-sequitur"
	)
	
	func main() {
		var g sequitur.Grammar
		if err := g.Parse([]byte(`°`)); err != nil {
			log.Fatal(err)
		}
		var buf bytes.Buffer
		g.PrettyPrint(&buf)
		fmt.Println(utf8.Valid(buf.Bytes()))
	}

**Comment by elliott5** [comment]
See PR#1 :)

**Comment by dgryski** [comment]
I think this is done now that https://github.com/dgryski/go-sequitur/pull/1 is merged.
